---

parser: babel-eslint

env:
  browser: true
  node: true
  jest:
    "jest/globals": true
  
extends:
  - airbnb-base
  - "plugin:react/recommended"
  - "plugin:import/react"
  - "plugin:flowtype/recommended"

plugins:
  - flowtype

settings:
  "import/resolver":
    node:
      extensions:
        - ".js"
        - ".jsx"
  react:
    version: "16.6"
